# This file was generated by GoReleaser. DO NOT EDIT.
cask "web-researcher-mcp" do
  version "1.49.3"

  on_macos do
    on_arm do
      sha256 "ee2ed0cad795f059f4685360448f689b1eb187b45833de0e5b36b062b6631698"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8db8ca8b26ff2d61514f99e1817a2d835e45fc1384d789c969836c8dfee520e8"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aaf1ac512861fa0fc249b53ba45565700b7b4ebb73e454385856fb16388bee06"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "02577a3379b8488e315a52016fea63d19714603270c7bf50fe84be94baf5f346"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_linux_amd64.tar.gz"
    end
  end

  name "web-researcher-mcp"
  desc "Your AI research assistant that cites real sources and stays honest"
  homepage "https://github.com/zoharbabin/web-researcher-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "web-researcher-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/web-researcher-mcp"],
                     sudo: false
    end
  end

  # No zap stanza required
end
