# This file was generated by GoReleaser. DO NOT EDIT.
cask "web-researcher-mcp" do
  version "1.37.5"

  on_macos do
    on_intel do
      sha256 "f89e6a2d6e3ea58a0332f2db5c6ec47aaf4d371a181dca5fecab3c4ff065392d"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e8fc64e1c17c999babab82a85cd8953d3b306e32de5fe48084c8881a20176e0"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46675fc54287c1f124d99fafe6d068b9f7276a20b3701447d58a08324e9c992c"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd4acdf7d4dc4b13268faa46c084202e4a504e5f3f0d0d7e8eece36cb4441acd"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "web-researcher-mcp"
  desc "Your AI research assistant that cites real sources and stays honest"
  homepage "https://github.com/zoharbabin/web-researcher-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "web-researcher-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/web-researcher-mcp"],
                     sudo: false
    end
  end

  # No zap stanza required

end
