# This file was generated by GoReleaser. DO NOT EDIT.
cask "web-researcher-mcp" do
  version "1.20.2"

  on_macos do
    on_intel do
      sha256 "5f07ea13628c4c4a07eca3ec92714b4806c3f5583440a547f31469764808e875"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5382a225a25458840e85192917a468a197489a454158667ca706283a96092b2d"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a31ecdee046e1406af0206d9228c5802dc199b04a7c40cf3198423377f825087"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "213841553434d613f51809f67416ab5bfe651246f0a3aeffb0087ec28652e6f0"
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v#{version}/web-researcher-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "web-researcher-mcp"
  desc "Your AI research assistant that cites real sources and stays honest"
  homepage "https://github.com/zoharbabin/web-researcher-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "web-researcher-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/web-researcher-mcp"],
                     sudo: false
    end
  end

  # No zap stanza required

end
