# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebResearcherMcp < Formula
  desc "Your AI research assistant that cites real sources and stays honest"
  homepage "https://github.com/zoharbabin/web-researcher-mcp"
  version "1.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v1.10.1/web-researcher-mcp_1.10.1_darwin_amd64.tar.gz"
      sha256 "af387f88a99f4d19061b842952ea51c14a9b05480bac3df4c72e6c3d2566d292"

      define_method(:install) do
        bin.install "web-researcher-mcp"
        (share/"web-researcher-mcp/lenses").install Dir["lenses/*"] if Dir.exist?("lenses")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v1.10.1/web-researcher-mcp_1.10.1_darwin_arm64.tar.gz"
      sha256 "18cc3e20dede254ea666c9d37131a652523e564c3aad9cda2fefef3a1e3e7185"

      define_method(:install) do
        bin.install "web-researcher-mcp"
        (share/"web-researcher-mcp/lenses").install Dir["lenses/*"] if Dir.exist?("lenses")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v1.10.1/web-researcher-mcp_1.10.1_linux_amd64.tar.gz"
      sha256 "759a79252c1f9029fe53cf3c108e2514634054f8e7b58487c79b52f07befb0dc"
      define_method(:install) do
        bin.install "web-researcher-mcp"
        (share/"web-researcher-mcp/lenses").install Dir["lenses/*"] if Dir.exist?("lenses")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zoharbabin/web-researcher-mcp/releases/download/v1.10.1/web-researcher-mcp_1.10.1_linux_arm64.tar.gz"
      sha256 "a3660b731df5d062de293df65689a89b1ec37479a7fcfb7ce2c834126aafc9ba"
      define_method(:install) do
        bin.install "web-researcher-mcp"
        (share/"web-researcher-mcp/lenses").install Dir["lenses/*"] if Dir.exist?("lenses")
      end
    end
  end

  test do
    system "#{bin}/web-researcher-mcp", "--help"
  end
end
